spring.application.name=review-service
server.port=8086

spring.data.mongodb.uri=mongodb://localhost:27017/reviewsdb

spring.data.mongodb.auto-index-creation=true

eureka.client.service-url.defaultZone=http://localhost:8083/eureka/
eureka.instance.prefer-ip-address=true

# Keycloak JWT Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/wassalni-realm
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8080/realms/wassalni-realm/protocol/openid-connect/certs
