spring.application.name=toxicity-service
server.port=8089

eureka.client.service-url.defaultZone=http://localhost:8083/eureka/
eureka.instance.prefer-ip-address=true
gemini.api.key=AIzaSyDjjEzOl100jEKG_63LIT6lFWNGxm5RGZo